//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/DMTKActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @DMTKActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @DMTKActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""DMTKActions"",
    ""maps"": [
        {
            ""name"": ""DMTKPlayer"",
            ""id"": ""0fb9da05-fd55-4605-a725-89842b223a64"",
            ""actions"": [
                {
                    ""name"": ""ConservativeResize"",
                    ""type"": ""Button"",
                    ""id"": ""cfc2c655-ab62-4864-8210-c81002541601"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseDown"",
                    ""type"": ""Button"",
                    ""id"": ""d8604eda-6c72-40fe-93f6-4718adb0f6df"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseHold"",
                    ""type"": ""Button"",
                    ""id"": ""74eeea71-0112-47b1-aec9-299e1e2f7295"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TabDown"",
                    ""type"": ""Button"",
                    ""id"": ""5d85d882-d825-4b09-9635-e9807970dffb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""45c50c9a-75f4-440f-bafe-06c59a77630a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Scroll"",
                    ""type"": ""Value"",
                    ""id"": ""f8125a06-11ec-4349-acc7-e3dc6f2ddca6"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e7142955-1320-488a-804a-6758e9bf16f0"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": ""Hold(duration=0.01,pressPoint=0.01)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ConservativeResize"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e4fb7f80-3e8a-4999-bb53-7351f0fcc58f"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da07cb64-c313-464f-9eb6-04da24d17817"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5773c029-c7d5-496f-87a0-75db7a365b97"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TabDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fc2fb2c8-9971-4739-aaf2-31fc01f602c4"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Scroll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3226b5fe-f52c-4a29-bd4e-d07b4cc095ff"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // DMTKPlayer
        m_DMTKPlayer = asset.FindActionMap("DMTKPlayer", throwIfNotFound: true);
        m_DMTKPlayer_ConservativeResize = m_DMTKPlayer.FindAction("ConservativeResize", throwIfNotFound: true);
        m_DMTKPlayer_MouseDown = m_DMTKPlayer.FindAction("MouseDown", throwIfNotFound: true);
        m_DMTKPlayer_MouseHold = m_DMTKPlayer.FindAction("MouseHold", throwIfNotFound: true);
        m_DMTKPlayer_TabDown = m_DMTKPlayer.FindAction("TabDown", throwIfNotFound: true);
        m_DMTKPlayer_MousePosition = m_DMTKPlayer.FindAction("MousePosition", throwIfNotFound: true);
        m_DMTKPlayer_Scroll = m_DMTKPlayer.FindAction("Scroll", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // DMTKPlayer
    private readonly InputActionMap m_DMTKPlayer;
    private List<IDMTKPlayerActions> m_DMTKPlayerActionsCallbackInterfaces = new List<IDMTKPlayerActions>();
    private readonly InputAction m_DMTKPlayer_ConservativeResize;
    private readonly InputAction m_DMTKPlayer_MouseDown;
    private readonly InputAction m_DMTKPlayer_MouseHold;
    private readonly InputAction m_DMTKPlayer_TabDown;
    private readonly InputAction m_DMTKPlayer_MousePosition;
    private readonly InputAction m_DMTKPlayer_Scroll;
    public struct DMTKPlayerActions
    {
        private @DMTKActions m_Wrapper;
        public DMTKPlayerActions(@DMTKActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @ConservativeResize => m_Wrapper.m_DMTKPlayer_ConservativeResize;
        public InputAction @MouseDown => m_Wrapper.m_DMTKPlayer_MouseDown;
        public InputAction @MouseHold => m_Wrapper.m_DMTKPlayer_MouseHold;
        public InputAction @TabDown => m_Wrapper.m_DMTKPlayer_TabDown;
        public InputAction @MousePosition => m_Wrapper.m_DMTKPlayer_MousePosition;
        public InputAction @Scroll => m_Wrapper.m_DMTKPlayer_Scroll;
        public InputActionMap Get() { return m_Wrapper.m_DMTKPlayer; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DMTKPlayerActions set) { return set.Get(); }
        public void AddCallbacks(IDMTKPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_DMTKPlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DMTKPlayerActionsCallbackInterfaces.Add(instance);
            @ConservativeResize.started += instance.OnConservativeResize;
            @ConservativeResize.performed += instance.OnConservativeResize;
            @ConservativeResize.canceled += instance.OnConservativeResize;
            @MouseDown.started += instance.OnMouseDown;
            @MouseDown.performed += instance.OnMouseDown;
            @MouseDown.canceled += instance.OnMouseDown;
            @MouseHold.started += instance.OnMouseHold;
            @MouseHold.performed += instance.OnMouseHold;
            @MouseHold.canceled += instance.OnMouseHold;
            @TabDown.started += instance.OnTabDown;
            @TabDown.performed += instance.OnTabDown;
            @TabDown.canceled += instance.OnTabDown;
            @MousePosition.started += instance.OnMousePosition;
            @MousePosition.performed += instance.OnMousePosition;
            @MousePosition.canceled += instance.OnMousePosition;
            @Scroll.started += instance.OnScroll;
            @Scroll.performed += instance.OnScroll;
            @Scroll.canceled += instance.OnScroll;
        }

        private void UnregisterCallbacks(IDMTKPlayerActions instance)
        {
            @ConservativeResize.started -= instance.OnConservativeResize;
            @ConservativeResize.performed -= instance.OnConservativeResize;
            @ConservativeResize.canceled -= instance.OnConservativeResize;
            @MouseDown.started -= instance.OnMouseDown;
            @MouseDown.performed -= instance.OnMouseDown;
            @MouseDown.canceled -= instance.OnMouseDown;
            @MouseHold.started -= instance.OnMouseHold;
            @MouseHold.performed -= instance.OnMouseHold;
            @MouseHold.canceled -= instance.OnMouseHold;
            @TabDown.started -= instance.OnTabDown;
            @TabDown.performed -= instance.OnTabDown;
            @TabDown.canceled -= instance.OnTabDown;
            @MousePosition.started -= instance.OnMousePosition;
            @MousePosition.performed -= instance.OnMousePosition;
            @MousePosition.canceled -= instance.OnMousePosition;
            @Scroll.started -= instance.OnScroll;
            @Scroll.performed -= instance.OnScroll;
            @Scroll.canceled -= instance.OnScroll;
        }

        public void RemoveCallbacks(IDMTKPlayerActions instance)
        {
            if (m_Wrapper.m_DMTKPlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDMTKPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_DMTKPlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DMTKPlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DMTKPlayerActions @DMTKPlayer => new DMTKPlayerActions(this);
    public interface IDMTKPlayerActions
    {
        void OnConservativeResize(InputAction.CallbackContext context);
        void OnMouseDown(InputAction.CallbackContext context);
        void OnMouseHold(InputAction.CallbackContext context);
        void OnTabDown(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
        void OnScroll(InputAction.CallbackContext context);
    }
}
