//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/DMTKActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @DMTKActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @DMTKActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""DMTKActions"",
    ""maps"": [
        {
            ""name"": ""DMTKPlayer"",
            ""id"": ""0fb9da05-fd55-4605-a725-89842b223a64"",
            ""actions"": [
                {
                    ""name"": ""ConservativeResize"",
                    ""type"": ""Button"",
                    ""id"": ""cfc2c655-ab62-4864-8210-c81002541601"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e7142955-1320-488a-804a-6758e9bf16f0"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": ""Hold(duration=0.01,pressPoint=0.01)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ConservativeResize"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // DMTKPlayer
        m_DMTKPlayer = asset.FindActionMap("DMTKPlayer", throwIfNotFound: true);
        m_DMTKPlayer_ConservativeResize = m_DMTKPlayer.FindAction("ConservativeResize", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // DMTKPlayer
    private readonly InputActionMap m_DMTKPlayer;
    private List<IDMTKPlayerActions> m_DMTKPlayerActionsCallbackInterfaces = new List<IDMTKPlayerActions>();
    private readonly InputAction m_DMTKPlayer_ConservativeResize;
    public struct DMTKPlayerActions
    {
        private @DMTKActions m_Wrapper;
        public DMTKPlayerActions(@DMTKActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @ConservativeResize => m_Wrapper.m_DMTKPlayer_ConservativeResize;
        public InputActionMap Get() { return m_Wrapper.m_DMTKPlayer; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DMTKPlayerActions set) { return set.Get(); }
        public void AddCallbacks(IDMTKPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_DMTKPlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DMTKPlayerActionsCallbackInterfaces.Add(instance);
            @ConservativeResize.started += instance.OnConservativeResize;
            @ConservativeResize.performed += instance.OnConservativeResize;
            @ConservativeResize.canceled += instance.OnConservativeResize;
        }

        private void UnregisterCallbacks(IDMTKPlayerActions instance)
        {
            @ConservativeResize.started -= instance.OnConservativeResize;
            @ConservativeResize.performed -= instance.OnConservativeResize;
            @ConservativeResize.canceled -= instance.OnConservativeResize;
        }

        public void RemoveCallbacks(IDMTKPlayerActions instance)
        {
            if (m_Wrapper.m_DMTKPlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDMTKPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_DMTKPlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DMTKPlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DMTKPlayerActions @DMTKPlayer => new DMTKPlayerActions(this);
    public interface IDMTKPlayerActions
    {
        void OnConservativeResize(InputAction.CallbackContext context);
    }
}
